name: Package
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * MON'

concurrency:
  group: '${{ github.ref }}'
  cancel-in-progress: true

jobs:
  package:
    name: Build and upload the image (${{ matrix.version }})
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        version:
          - latest
          - 19
          - 18
          - 16
          - 14
    steps:
      - name: Prepare the virtual environment
        uses: hausgold/actions/ci@master
        with:
          clone_token: '${{ secrets.CLONE_TOKEN }}'
          settings_secret_key: '${{ secrets.SETTINGS_SECRET_KEY }}'
          settings: '${{ github.repository }}'
          target: ci/noop
      - uses: actions/checkout@v3

      - name: Configure IMAGE_REF
        run: var IMAGE_REF '${{ matrix.version }}'

      - name: Build the Docker image
        run: make -C '${{ matrix.version }}' build

      - name: Run the Smoke Test on the Docker image
        run: make -C '${{ matrix.version }}' test

      - name: Upload the Docker image
        run: make -C '${{ matrix.version }}' publish
